name: spice_wallet
description: "A light Monero wallet."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: 3.11.5
  flutter: 3.41.7

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
    image_path: "assets/launcher_icon.png"
    icon_size: 48
  image_path: "assets/launcher_icon.png"
  adaptive_icon_background: "#263F5F"
  adaptive_icon_foreground: "assets/launcher_icon.png"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  tor_ffi_plugin:
    git:
      url: https://github.com/cypherstack/tor
      ref: main
  openalias_ffi:
    path: plugins/openalias_ffi
  monero:
    git:
      url: https://github.com/vtnerd/monero_c
      ref: lwsf
      path: impls/monero.dart
  cupertino_icons: 1.0.8
  path: 1.9.1
  provider: 6.1.5+1
  path_provider: 2.1.5
  dart_date: 1.5.3
  qr_flutter: 4.1.0
  share_plus: 11.1.0
  intl: 0.20.2
  shared_preferences: 2.5.3
  http: 1.6.0
  workmanager: 0.9.0+3
  flutter_foreground_task: 8.17.0
  flutter_local_notifications: 19.5.0
  timeago: 3.7.1
  flutter_riverpod: 2.6.1
  screen_brightness: 2.1.7
  flutter_zxing: 2.3.0
  permission_handler: 12.0.1
  flutter_svg: 2.2.3
  skeletonizer: 2.1.1
  flutter_secure_storage: 9.2.4
  local_auth: 2.3.0
  flutter_launcher_icons: 0.14.4
  gpt_markdown: 1.1.4
  polyseed: 0.0.7
  # The dart-bitcoin/bip39 repository has an unresolved issue that results in lower seed entropy
  # than ideal: https://github.com/dart-bitcoin/bip39/issues/23
  # It also is no longer maintained.
  # Cypher Stack (Stack Wallet) maintains a fork of this repository with a fix for this
  # (https://github.com/cypherstack/stack-bip39/commit/2e9bfc1387d6078c31b14356090ea6058046de72);
  # we use their repository to benefit from these improvements.
  bip39:
    git:
      url: https://github.com/cypherstack/stack-bip39
      ref: 0cd6d54e2860bea68fc50c801cb9db2a760192fb # master @ 2023-06-07, includes the entropy fix
  bip32: 2.0.0
  package_info_plus: 8.3.0
  pointycastle: 3.9.1
  bitcoin_base:
    git:
      url: https://github.com/cake-tech/bitcoin_base
      ref: cake-update-v11
  blockchain_utils:
    git:
      url: https://github.com/cake-tech/blockchain_utils
      ref: cake-update-v2
  webcrypto: 0.6.0
  web3dart: 2.7.1
  screen_protector: 1.5.2

dependency_overrides:
  hashlib: 1.19.2
  intl: any
  web3dart:
    git:
      url: https://github.com/cake-tech/web3dart.git
      ref: cake

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: 5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/cacert.pem
    - assets/app_icon.ico

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
